#!/bin/bash

# Gather the enthalpy values from glassy phase runs

../scripts/gather-glass-enthalpy.py\
	"/home/nerve/Documents/ben/rc/data"\
	"../gathered_data"\
	"100k_minimize_template.in"\
	"log.lammps"\
	"finaltraj.lammpstrj"\
